### PR TITLE
Fix osgEarth viewpoints ignoring SRS

### PR DESCRIPTION
**Pull request by fin-ger**
This PR fixes wrong (and deprecated) usage of the `osgEarth::Viewpoint` constructor. This patch makes it possible to use OSGEarth terrains from sources like [LOLA](https://ode.rsl.wustl.edu/moon/index.aspx) or [MOLA](https://ode.rsl.wustl.edu/mars/) with different celestial bodies. This is achieved by respecting the `SRS` when setting the viewpoints in an Omnet++ simulation.

This patch may or may not work for the current master branch. I have only tested this with the version 5 branch.

Edit: Add links to data sources

### CODE REVIEW

**Comment by torokati44** [comment]
Thanks for the fix! I've cherry-picked it into our internal repository. It worked fine on the master branch as well.

Just out of curiosity, could you perhaps tell us a bit more about why do you need OMNeT++ to work on other celestial bodies?
Sounds like quite an interesting project, we'd love to hear about it!

Also, I tried checking out those datasets, but couldn't find a way to make osgEarth use them, other than placing a few markers (on Earth...) from derived .kml files. Again, out of curiosity, how does one get image data and/or elevation from the mentioned datasets loaded into osgEarth?

**Comment by fin-ger** [comment]
Sure, a minimal working example (with INET) would look like this:

Download the `.img` and `.lbl` from the [`LDEM_1024_75S_60S_030_060`](https://ode.rsl.wustl.edu/moon/indexproductpage.aspx?product_id=LDEM_1024_75S_60S_030_060&product_idGeo=20762484) dataset.

<details>
<summary><code>boguslawsky.earth</code></summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<map name="Boguslawsky Crater" type="geodetic" version="2">
  <options>
    <terrain driver="mp" min_tile_range_factor="24" tile_size="64">
      <normalize_edges>true</normalize_edges>
    </terrain>
    <profile name="Moon_2000" srs="+proj=latlon +a=1737400 +b=1737400"></profile>
  </options>

  <elevation name="height" driver="gdal">
    <url>ldem_1024_75s_60s_030_060.lbl</url>
  </elevation>

  <viewpoints>
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky Bird's Eye"
        heading="0"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-90"
        range="200000"
        />
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky N"
        heading="0"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-20"
        range="120000"
        />
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky NE"
        heading="45"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-20"
        range="120000"
        />
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky E"
        heading="90"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-20"
        range="120000"
        />
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky SE"
        heading="135"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-20"
        range="120000"
        />
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky S"
        heading="180"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-20"
        range="120000"
        />
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky SW"
        heading="225"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-20"
        range="120000"
        />
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky W"
        heading="270"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-20"
        range="120000"
        />
    <viewpoint
        srs="+proj=latlon +a=1737400 +b=1737400"
        name="Boguslawsky NW"
        heading="315"
        height="30"
        lat="-72.9"
        long="43.3"
        pitch="-20"
        range="120000"
        />
  </viewpoints>

  <extensions>
    <sky driver="gl" hours="9.0"/>
  </extensions>
</map>
```

</details>

<details>
<summary><code>boguslawsky_crater.ned</code></summary>

```js
import inet.common.geometry.common.OsgGeographicCoordinateSystem;
import inet.environment.common.PhysicalEnvironment;
import inet.visualizer.integrated.IntegratedVisualizer;
import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.physicallayer.ieee80211.packetlevel.Ieee80211DimensionalRadioMedium;
import inet.node.inet.ManetRouter;

network BoguslawskyCrater {
    parameters:
        *.mobility.initFromDisplayString = false;
        *.mobility.coordinateSystemModule = "coordinateSystem";

    submodules:
        visualizer: IntegratedVisualizer {
            @display("p=300,50");
                
            osgVisualizer.typename = "IntegratedOsgVisualizer";
            osgVisualizer.sceneVisualizer.typename = "SceneOsgEarthVisualizer";
            osgVisualizer.sceneVisualizer.mapFile = "boguslawsky.earth";
            osgVisualizer.sceneVisualizer.zFar = 10000km;
            osgVisualizer.physicalLinkVisualizer.displayLinks = true;
            osgVisualizer.mediumVisualizer.displaySignals = true;
        }
        coordinateSystem: OsgGeographicCoordinateSystem {
            @display("p=300,150");
                
            sceneLatitude = -67.5deg;
            sceneLongitude = 45deg;
        }
        physicalEnvironment: PhysicalEnvironment {
            @display("p=300,300");
            ground.typename = "OsgEarthGround";
            ground.osgEarthSceneVisualizerModule = "visualizer.osgVisualizer.sceneVisualizer";
            ground.coordinateSystemModule = "coordinateSystem";
        }
        configurator: Ipv4NetworkConfigurator {
            @display("p=300,450");
        }
        radioMedium: Ieee80211DimensionalRadioMedium {
            @display("p=300,600");
            obstacleLoss.typename = "DielectricObstacleLoss";
        }
        SenderNode: ManetRouter {
            @display("p=100,100;i=device/antennatower");
            numApps = 1;

            app[0].typename = "UdpBasicApp";
            app[0].destAddresses = "EchoNode";
            app[0].destPort = 5000;
            app[0].messageLength = default(1000B);
            app[0].sendInterval = 5s;
            app[0].packetName = "DataA";

            mobility.typename = "StationaryMobility";
            mobility.initialAltitude = 10m;
            mobility.initialLatitude = -72.312deg;
            mobility.initialLongitude = 45.815deg;
        }
        EchoNode: ManetRouter {
            @display("p=100,500;i=misc/drone");
            numApps = 1;

            app[0].typename = "UdpEchoApp";
            app[0].localPort = 5000;

            mobility.typename = "StationaryMobility";
            mobility.initialAltitude = 2m;
            mobility.initialLatitude = -72.362deg;
            mobility.initialLongitude = 45.865deg;
        }
}
```

</details>

<details>
<summary><code>omnetpp.ini</code></summary>

```ini
[General]
*.configurator.addStaticRoutes = false
**.netmaskRoutes = ""
**.arp.typename = "GlobalArp"

# routing protocol parameters
*.*.routingApp.typename = "Aodv"
*.*.routingApp.activeRouteTimeout = 1s
*.*.routingApp.deletePeriod = 0.5s

[Config Boguslawsky-Crater-Example]
network = BoguslawskyCraterExample
```

</details>

Place all above files into an Omnet++ project and run it. I couldn't figure out yet how to place the initial camera view, therefore you have to look around in the simulation view to spot the Boguslawsky crater where the two nodes are placed.

image

> Note: This example is only known to work with OSGEarth 2.10. Versions below 2.10 are known to cause issues (black screen, flickering, etc.). Version 3.0 has not been tested, yet.

To just view the crater with OSGEarth you can run

```
$ osgearth_viewer boguslawsky.earth
```

Use the predefined viewpoints in OSGEarth to quickly navigate to the Boguslawsky crater (1-9).

image

> Note: I think the amplitude of the terrain is twice as high as it should be. I'm currently investigating on this in GDAL (the pre-scaling factor of the PDS data seems to be ignored).

**Comment by torokati44** [comment]
Thanks for the instructions! This looks so cool!

I see this is your masters thesis, right? Let us know when it's done, so we can check it out!

> Note: This example is only known to work with OSGEarth 2.10. Versions below 2.10 are known to cause issues (black screen, flickering, etc.).

Good to know.

> Version 3.0 has not been tested, yet.

 I doubt that OMNeT++/Qtenv would even compile with osgEarth 3.0, as it is only about three weeks old, and we haven't yet verified our compatibility with the new major version either.

> I couldn't figure out yet how to place the initial camera view, therefore you have to look around in the simulation view to spot the Boguslawsky crater where the two nodes are placed.

`cOsgCanvas::setEarthViewpoint(const EarthViewpoint& earthViewpoint);` might be what you need.

**Comment by fin-ger** [comment]
> I see this is your masters thesis, right? Let us know when it's done, so we can check it out!

Right! I'll be happy to let you know.

> `cOsgCanvas::setEarthViewpoint(const EarthViewpoint& earthViewpoint);` might be what you need.

Yes! Thank you, this helped a lot.

For reference, if anyone reading this thread wonders how I solved this, I created a custom `SceneOsgEarthVisualizer` which can set the viewport via NED parameters:

<details>
<summary><code>boguslawsky_crater.ned</code></summary>

```js
import inet.common.geometry.common.OsgGeographicCoordinateSystem;
import inet.environment.common.PhysicalEnvironment;
import inet.visualizer.integrated.IntegratedVisualizer;
import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.physicallayer.ieee80211.packetlevel.Ieee80211DimensionalRadioMedium;
import inet.node.inet.ManetRouter;

network BoguslawskyCrater {
    parameters:
        *.mobility.initFromDisplayString = false;
        *.mobility.coordinateSystemModule = "coordinateSystem";

    submodules:
        visualizer: IntegratedVisualizer {
            @display("p=300,50");
                
            osgVisualizer.typename = "IntegratedOsgVisualizer";
            osgVisualizer.sceneVisualizer.typename = "EnhancedSceneOsgEarthVisualizer";
            osgVisualizer.sceneVisualizer.mapFile = "boguslawsky.earth";
            osgVisualizer.sceneVisualizer.zFar = 10000km;
            osgVisualizer.sceneVisualizer.viewpointLongitude = 45.44deg;
            osgVisualizer.sceneVisualizer.viewpointLatitude = -72.34deg;
            osgVisualizer.sceneVisualizer.viewpointAltitude = 10m;
            osgVisualizer.sceneVisualizer.viewpointHeading = 90deg;
            osgVisualizer.sceneVisualizer.viewpointPitch = 10deg;
            osgVisualizer.sceneVisualizer.viewpointRange = 1m;
            osgVisualizer.physicalLinkVisualizer.displayLinks = true;
            osgVisualizer.mediumVisualizer.displaySignals = true;
        }
        coordinateSystem: OsgGeographicCoordinateSystem {
            @display("p=300,150");
                
            sceneLatitude = -67.5deg;
            sceneLongitude = 45deg;
        }
        physicalEnvironment: PhysicalEnvironment {
            @display("p=300,300");
            ground.typename = "OsgEarthGround";
            ground.osgEarthSceneVisualizerModule = "visualizer.osgVisualizer.sceneVisualizer";
            ground.coordinateSystemModule = "coordinateSystem";
        }
        configurator: Ipv4NetworkConfigurator {
            @display("p=300,450");
        }
        radioMedium: Ieee80211DimensionalRadioMedium {
            @display("p=300,600");
            obstacleLoss.typename = "DielectricObstacleLoss";
        }
        SenderNode: ManetRouter {
            @display("p=100,100;i=device/antennatower");
            numApps = 1;

            app[0].typename = "UdpBasicApp";
            app[0].destAddresses = "EchoNode";
            app[0].destPort = 5000;
            app[0].messageLength = default(1000B);
            app[0].sendInterval = 5s;
            app[0].packetName = "DataA";

            mobility.typename = "StationaryMobility";
            mobility.initialAltitude = 10m;
            mobility.initialLatitude = -72.312deg;
            mobility.initialLongitude = 45.815deg;
        }
        EchoNode: ManetRouter {
            @display("p=100,500;i=misc/drone");
            numApps = 1;

            app[0].typename = "UdpEchoApp";
            app[0].localPort = 5000;

            mobility.typename = "StationaryMobility";
            mobility.initialAltitude = 2m;
            mobility.initialLatitude = -72.362deg;
            mobility.initialLongitude = 45.865deg;
        }
}
```

</details>

<details>
<summary><code>EnhancedSceneOsgEarthVisualizer.ned</code></summary>

```js
package master_thesis;

import inet.visualizer.scene.SceneOsgEarthVisualizer;
import inet.visualizer.contract.ISceneVisualizer;

simple EnhancedSceneOsgEarthVisualizer extends SceneOsgEarthVisualizer
{
    parameters:
        @class(master_thesis::EnhancedSceneOsgEarthVisualizer);
        double viewpointLongitude @unit(deg);
        double viewpointLatitude @unit(deg);
        double viewpointAltitude @unit(m);
        double viewpointHeading @unit(deg) = default(0deg);
        double viewpointPitch @unit(deg) = default(0deg);
        double viewpointRange @unit(m) = default(0m);
}
```

</details>

<details>
<summary><code>EnhancedSceneOsgEarthVisualizer.h</code></summary>

```cpp
#ifndef ENHANCEDSCENEOSGEARTHVISUALIZER_H_
#define ENHANCEDSCENEOSGEARTHVISUALIZER_H_

#include "inet/visualizer/scene/SceneOsgEarthVisualizer.h"

using namespace inet::visualizer;

namespace master_thesis {
    class EnhancedSceneOsgEarthVisualizer : public SceneOsgEarthVisualizer {
    protected:
        virtual void initializeViewpoint();
    };
}

#endif /* ENHANCEDSCENEOSGEARTHVISUALIZER_H_ */
```

</details>

<details>
<summary><code>EnhancedSceneOsgEarthVisualizer.cc</code></summary>

```cpp
#include "EnhancedSceneOsgEarthVisualizer.h"

namespace master_thesis {

Define_Module(EnhancedSceneOsgEarthVisualizer);

void EnhancedSceneOsgEarthVisualizer::initializeViewpoint() {
    double longitude = this->par("viewpointLongitude");
    double latitude = this->par("viewpointLatitude");
    double altitude = this->par("viewpointAltitude");
    double heading = this->par("viewpointHeading");
    double pitch = this->par("viewpointPitch");
    double range = this->par("viewpointRange");
    auto osgCanvas = visualizationTargetModule->getOsgCanvas();
    osgCanvas->setEarthViewpoint(
        inet::cOsgCanvas::EarthViewpoint(
            longitude,
            latitude,
            altitude,
            heading,
            pitch,
            range
        )
    );
}
}
```

</details>

**Comment by fin-ger** [comment]
> I see this is your masters thesis, right? Let us know when it's done, so we can check it out!

I finished and successfully defended my master thesis a couple of months ago, and finally all the documents are ready and it is published on the [university's website](http://comsys.ovgu.de/-p-690.html) ([direct PDF link](http://comsys.ovgu.de/comsys_media/thesis/finished/MSc/2021+_+Fin+Christensen+_+Swarm+Communication+in+Space-p-514.pdf)).

> Note: the link may become invalid in a couple of years, I will add a reference to DLR's electronic library once it's available.

**Pull request closed without merging**
