### PR TITLE
Prevent histograms of numbers close to double::denorm_min() from crashing simulation

### LINKED ISSUE #863: Very small values in a histogram (from INET BER) cause floating point maths bug
**Platform**
 - OMNeT++ version: 5.6.2
 - OS: Windows (not relevant)

**Describe the bug**
*Very* small values in a histogram cause runtime error to be thrown in `cHistogram::createUniformBins(..,..,..)` when using `cDefaultHistogramStrategy::createBins()`
because of the following line.
https://github.com/omnetpp/omnetpp/blob/8f4b83553716dca653c93b1f83f49bdd2b5154ba/src/sim/chistogramstrategy.cc#L330

**To Reproduce**
Record a histogram with the following values `0, 1.9762625833649862e-323, 1.9762625833649862e-323`

Following the code through manually with commented values
```cpp
void cDefaultHistogramStrategy::createBins()
{
    targetNumBins = numBinsHint == -1 ? DEFAULT_NUM_BINS : numBinsHint; //60

    if (values.empty()) { //false
        this->binSize = 1;
        hist->createUniformBins(0, 1, binSize);
        return;
    }

    // determine mode (integers or reals) from precollected observations
    Mode mode = this->mode; //cHistogram::MODE_REALS

    if (mode == cHistogram::MODE_AUTO) { //false
        bool allIntegers = true;
        bool allZeroes = true;
        for (size_t i = 0; i < values.size(); i++) {
            if (allIntegers && values[i] != std::floor(values[i]))
                allIntegers = false;
            if (allZeroes && values[i] != 0)
                allZeroes = false;
        }

        mode = (allIntegers && !allZeroes) ? cHistogram::MODE_INTEGERS : cHistogram::MODE_REALS;
    }

    // compute histogram
    double minValue = finiteMinValue; // 1.9762625833649862e-323
    double maxValue = finiteMaxValue; // 0

    double c = (minValue + maxValue) / 2; // 9.8813129168249309e-324
    double r = (maxValue - minValue) * rangeExtensionFactor; // 2.9643938750474793e-323
    if (r == 0) // false
        r = 1.0;  // warning?

    // these might still be the same value because of double imprecision
    double rangeMin = c - r / 2; // -4.9406564584124654e-324
    double rangeMax = c + r / 2; // 2.4703282292062327e-323

    if (rangeMin < 0 && minValue >= 0 && maxValue > 0) // true
        rangeMin = 0; // do not go into negative unless warranted by the collected data // 0

    // just to avoid dividing by zero...
    if (rangeMin == rangeMax) //false
        binSize = 1;
    else {
        binSize = (rangeMax - rangeMin) / targetNumBins; // !!! 0 !!!
        binSize = roundToOneTwoFive(binSize);
    }
    if (mode == cHistogram::MODE_INTEGERS)
        binSize = ceil(binSize);

    rangeMin = binSize * std::floor(rangeMin / binSize); // snap // nan
    rangeMax = binSize * std::ceil(rangeMax / binSize);  // nan
    if (rangeMin == rangeMax) { // this can still happen if the single collected value is around 1e17 // false
        rangeMax = nextafter(rangeMin, INFINITY);
        binSize = rangeMax - rangeMin; // this should help avoid further problems (unless we are right where the precision drops even further)
    }
    hist->createUniformBins(rangeMin, rangeMax, binSize); // ERROR: binSize == 0

    ...
}
```

### PR DESCRIPTION
**Pull request by edlongman**
The current check for preventing `binSizes=0` was not enough. If the range was very small, it would still be zero due to the limits of precision of doubles.

It might be better instead of setting `binSize = 1` to setting it to `binSize = std::numeric_limits<double>::denorm_min()`
however this is then more likely to cause problems with the remaining  ` / targetNumBins` occurances in `binMerging` chistogram:L646 and `mergeAllBinsIntoOne()`

New tests are: 
* produce the smallest possible bins as well 
* default to bin size of 1 when all collected numbers are below the limiting precision.

Fixes #863

### CODE REVIEW

**Comment by torokati44** [comment]
Thank you for the fixes and the tests! They all look great to me.

**Comment by torokati44** [comment]
Actually, does the `cHistogram_cDefaultHistogramStrategy_1.test ` test pass for you? For me it breaks, but not on one of the new tests.

```
- 620 630 640 650 660 670 680 690 700 710 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990 1000 1010 1020 1030 1040 1050 1060 1070
+ 620 630 640 650 660 670 680 690 700 710 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990 1000 1010 1020 1030 1040 1050 1060 1070 1080
?                                                                                                                                                                                                +++++
```

**Comment by torokati44** [comment]
I am fine with adjusting the expected output to match what I get now, but if it passes for you as it is, then we have some sort of undeterministic thing going on... Which may or may not be a separate issue from this.

**Comment by edlongman** [comment]
Yes, the test passed for me.
I'm on omnet 5.6.2 but that shouldn't make a difference.
Did it pass before my modification?

**Comment by torokati44** [comment]
Yes, it does pass on `master`, but not with these changes rebased onto it.

**Comment by edlongman** [comment]
I had inadvertently changed my `.test` without commiting the change! 
I have found the problem with the old test. The old test was not picking up the full output (the extra 1080 was on the output) so the test is wrong and the output is the same! 

## Before changes
```
$ cat work/cHistogram_cDefaultHistogramStrategy_1/test.out
...
Running simulation...
** Event #1  t=0   Test (Test, id=1)
0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 1.1 1.2 1.3
0 1 2
0 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300
0 100 200 300 400 500 600 700 800 900 1000 1100 1200
987 988 989 990 991 992 993 994 995 996 997 998 999 1000 1001 1002 1003
987 988 989 990 991 992 993 994 995 996 997 998 999 1000 1001 1002 1003
620 630 640 650 660 670 680 690 700 710 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990 1000 1010 1020 1030 1040 1050 1060 1070 1080
620 630 640 650 660 670 680 690 700 710 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990 1000 1010 1020 1030 1040 1050 1060 1070 1080

<!> No more events, simulation completed -- at t=0s, event #1

Calling finish() at end of Run #0...

End.
```

```
$ cat work/cHistogram_cDefaultHistogramStrategy_1/test.out
...
Running simulation...
** Event #1  t=0   Test (Test, id=1)
0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 1.1 1.2 1.3
0 1 2
0 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300
0 100 200 300 400 500 600 700 800 900 1000 1100 1200
987 988 989 990 991 992 993 994 995 996 997 998 999 1000 1001 1002 1003
987 988 989 990 991 992 993 994 995 996 997 998 999 1000 1001 1002 1003
620 630 640 650 660 670 680 690 700 710 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990 1000 1010 1020 1030 1040 1050 1060 1070 1080
620 630 640 650 660 670 680 690 700 710 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900 910 920 930 940 950 960 970 980 990 1000 1010 1020 1030 1040 1050 1060 1070 1080
0 9.88131e-324 1.97626e-323 2.96439e-323 3.95253e-323 4.94066e-323 5.92879e-323 6.91692e-323 7.90505e-323 8.89318e-323 9.88131e-323 1.08694e-322 1.18576e-322 1.28457e-322 1.38338e-322 1.4822e-322 1.58101e-322 1.67982e-322 1.77864e-322 1.87745e-322 1.97626e-322 2.07508e-322 2.17389e-322 2.2727e-322 2.37152e-322 2.47033e-322 2.56914e-322 2.66795e-322 2.76677e-322 2.86558e-322 2.96439e-322
0 1

<!> No more events, simulation completed -- at t=0s, event #1

Calling finish() at end of Run #0...

End.
```

**Comment by torokati44** [comment]
Ah, I see. And what exactly could have caused this other histogram (seemingly unaffected by the fix) to change?

**Comment by edlongman** [comment]
I don't think the histogram has changed.

If, before applying the changes,  you look at the actual output
(work/cHistogram..../test.out)  it already contains that same distribution
of bins.

**Comment by torokati44** [comment]
Sure, not the actual data, I mean the bin setup only.
- Not that it's critical at all, I just wish to understand...

**Comment by edlongman** [comment]
I appreciate that! 
I'm not sure I'm explaining it very well. 

As I understand it the test suite does the following
Run the test putting stdout -> test.out
This results in 

> 
> **some expected output
> ... 1070** 1080
> 
>
> <!> No more events, simulation completed -- at t=0s, event #1
>
> Calling finish() at end of Run #0...

The test contains the following section listing 
```
%contains: stdout
some expected output
...1070
```
Which is matched as highlighted above

When I append the tests for the denormal numbers the test becomes

```
%contains: stdout
some expected output
...1070
my expected output
```

but this does not match the actual output 
> 
> **some expected output
> ... 1070** 1080
> **my expected output**
> 
>
> <!> No more events, simulation completed -- at t=0s, event #1
>
> Calling finish() at end of Run #0...

because of the trailing 1080

**Comment by torokati44** [comment]
Yes, this entire mechanism I understand, what I'm asking is: _why_ does that 1080 suddenly appear?
(But never mind though, this PR is already on its way to `master`. :) )

**Comment by torokati44** [comment]
Your changes are now included in `master`, thank you so much!

**Pull request closed without merging**
