### PR TITLE
Fix macOS compatibility issues

### PR DESCRIPTION
**Pull request by mhaeuser**
Currently, when building on a macOS host, there are two issues:

- The build environment usually requires exporting compiler and linker flags to include homebrew search paths. For some reason (possibly autoconf compatibility with broken terminals?), even when exported in a separate command prior, `ac_configure_args` picks them up as arguments to the configure script. Said script mishandles spaces and their quotation, causing errors when parsing `CFLAGS` and `LDFLAGS`.
- With the standard ABI, there is no definite cValue constructor for values of type long. Passing the result of `PyLong_AsLong` thus yields ambiguity errors.

Both issues are resolved trivially and should not cause regressions for other platforms.

### CODE REVIEW

**Comment by mhaeuser** [comment]
Happy new year! Anything missing here? :)

**Comment by rhornig** [comment]
Thanks for the report. It would be much better if
- you could report separate problems in separate issues and especially separate pull requests.
- State what the actual problem is, how to reproduce it and what is the context (omnet version etc.)

I'm assuming you are trying to build OMNeT++ master branch with homebrew. But I'm not sure on the architecture (x86_64 or aarch64 ???). It would be better to see the exact problem, before seeing a solution in a pull request.

Regarding the missing cValue(long) constructor: we are explicitly trying to avoid using long type in the OMNeT++ API. The reason is that `long` is 32 bit on Windows ABI (even on x86_64) while it is 64 bit on other systems so it can cause regressions.

**Comment by mhaeuser** [comment]
I understand why you want to separate the issues, but I have limited bandwidth right now and the changes are minimal, so I'd prefer sticking to the joint PR, if that is acceptable.

Regarding problem descriptions - sorry, but the commit messages are *very* detailed. For the first issue, you have the exact variables and exact values that cause issues (as reference examples, you can pick any other combo), the technical cause of the issue, and the corrected result after applying the fix. For the second problem, the issue is obvious, you have the location of the issue and the source of the ambiguity.

Yes, I build the master branch (the one I PR'd against) with libraries from homebrew (this doesn't really matter, it just imposes having to define variables that trigger the first issue). The issues are both architecture (but not ABI!) independent - but I use aarch64, if that matters.

Regarding long cValues, well, as I said, this comes from ``PyLong_AsLong``. Do you want it casted to ``intval_t`` by the caller instead? This will not keep callers from passing ``long`` though still, unless you happen to have a "problematic" ABI like aarch64 macOS. The new constructor cannot cause regressions, as it always casts to a type as large or larger (well, for the supported ABIs anyway, there is no upper limit for ``long``, but neither is there for ``int``).

**Comment by rhornig** [comment]
Yeah. I just figured there are long commit messages after looking into the commits directly. No need to separate these as we will handle this separately anyway. 

The configure script is indeed in bad shape regarding the variable parsing. I will take a look. I would like to test/fix with homebrew anyway, so that will be the good time to also add this fixes. Right now we support only the NIX package manager on macOS aarch64 with the `opp_env` tool, but homebrew is a definite must. (I plan to drop bundled toolchain/debendencies from the macOS builds. Those were used in the x86_64 builds but they are no longer feasible with the aarch64 architecture and the code signing requirements).

Just out of curiosity: why you are using the master branch. You are tinkering with the python integration there?

**Comment by mhaeuser** [comment]
> Just out of curiosity: why you are using the master branch. You are tinkering with the python integration there?
No particular reason, I thought it was the main development branch and that is where fixes should go. :)

Thanks!

**Comment by rhornig** [comment]
Ahh ok. 'master' is our development branch and can get quite turbulent as we introduce new features there. If you need stable fixes, I recommend `omnetpp-6.0.x` where only bugfixes go (so it's quite stable). Or `omnetpp-6.x` where the next version is taking shape. `master` is where the future 7.0 is developed (i.e. you may see backward incompatible changes).

If you are on macOS / aarch64 I would also suggest trying `opp_env` which is our own NIX based package and model management tool. With that, we also officially support macOS / aarch64 on omnetpp 6.0.2

**Comment by rhornig** [comment]
The change for the configure script got included in the 6.0.x branch and eventually it will find its way to the 6.x and master branch. Thanks a lot for the report/analysis/fix.

As for the cValue long constructor: we made the decision not to use (or avoid as much as possible) using the `long` type in the OMNeT++ API. It caused a lot of issues interfering with various other integer types. It is also not recommended to use `long` type in your models. If a user insist using the long type she must cast the type explicitly before passing to an omnet API.

**Comment by rhornig** [comment]
sorry. forgot to push the branch to the public repo. Here it is: 75d5ee524115a42c65b3e896a2ea80c63089326f

**Pull request closed without merging**
